version: '3.7'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies_catalog_dev
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-container
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      URL_DATASOURCE: jdbc:postgresql://postgres:5432/movies_catalog_dev
      USERNAME: postgres
      PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ~/.m2:/root/.m2