version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-container
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      URL_DATASOURCE: jdbc:postgresql://postgres:5432/movies_dev
      USERNAME: postgres
      PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ~/.m2:/root/.m2